export const SITE_URL = "https://astrocall.live";

export const HOROSCOPE_SIGNS = [
  "aries",
  "taurus",
  "aquarius",
  "cancer",
  "capricorn",
  "gemini",
  "leo",
  "libra",
  "pisces",
  "sagittarius",
  "scorpio",
  "virgo",
];

/** Public static routes (App Router paths). Category 1 SEO pages included. */
export const STATIC_SITEMAP_ROUTES = [
  "",
  "/privacy-policy",
  "/TermsOfUse",
  "/CookiePolicy",
  "/Disclaimer",
  "/RefundCancellation",
  "/ShippingDeliveryPolicy",
  "/StoreRefundPolicy",
  "/VedicAstrology",
  "/Numerology",
  "/TarotReading",
  "/PalmReading",
  "/AIAstrologer",
  "/BreakupAndDivorce",
  "/CareersAndJob",
  "/Cheating",
  "/KidsAndEducation",
  "/LoveAndRelation",
  "/MaritalLife",
  "/RelationCounceling",
  "/Muhurat",
  "/VratUpvaas",
  "/Upcomingfestival",
  "/today-panchang",
  "/daily-horoscope",
  "/astrology-blog",
  "/freekundli",
  "/kundali-matching",
  "/love-calculator",
  "/gemstone",
  "/online-puja",
  "/talk-to-astrologers",
  "/chat-to-astrologers",
  "/reels",
  "/support",
  "/plans",
  "/wait-list",
  "/astrologer-login",
  "/astrologer-register",
  "/suggested",
];
